version: 2.1
jobs:
  compile:
   docker:
      - image: fajar4561/saciku:latest
   steps:
      - run:
          command: |
            git config --global user.name "fajar4561"
            git config --global user.email "maulanafajar751@gmail.com"
            git clone --depth=1 https://$AWAL:$AKHIR@github.com/fajar4561/Kernel_Asus_SDM660 -b caf-eas kernel && cd kernel
            curl https://raw.githubusercontent.com/fajar4561/My-kernel-builder/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 