version: 2.1
jobs:
  compile:
   docker:
      - image: fajar4561/aosp-builder:latest
   environment:
    FOO: bar
    parallelism: 4
    resource_class: large
   steps:
      - restore_cache:
          key: deps1-{{ .Branch }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            git config --global user.name "fajar4561"
            git config --global user.email "maulanafajar751@gmail.com"
            cd /tmp
            git clone --depth=1 https://$AWAL:$AKHIR@github.com/fajar4561/Kernel_Asus_SDM660 -b master-caf kernel && cd kernel
            curl https://raw.githubusercontent.com/fajar4561/CI-Kernel-Builder/master/build.sh > run.sh
            source run.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile  
