version: 2.1
jobs:
  compile:
   docker:
      - image: fajar4561/aosp-builder:latest
   
   steps:
      - run:
          command: |
            cd ..
            git config --global user.name "fajar4561"
            git config --global user.email "maulanafajar751@gmail.com"
            source env.sh
            git clone --depth=1 $KERNEL_REPO -b $KERNEL_BRANCH kernel
            source build.sh
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile  
